export const SET_EXERCISES_ACTIVE_LIST = 'SET_EXERCISES_ACTIVE_LIST';
export const CLEAR_EXERCISES = 'CLEAR_EXERCISES';
export const SET_ACTIVE_EXERCISE = 'SET_ACTIVE_EXERCISE';
export const UPDATE_ACTIVE_LIST = 'UPDATE_ACTIVE_LIST';
